"""add description and tags

Revision ID: 396b0f3249f0
Revises: 4f65af5f2544
Create Date: 2026-04-19 20:32:46.371861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '396b0f3249f0'
down_revision: Union[str, None] = '4f65af5f2544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'tags')
    op.drop_column('nodes', 'description')
    # ### end Alembic commands ###
