"""add_rag_content

Revision ID: 4f46bb79aa8a
Revises: 396b0f3249f0
Create Date: 2026-04-20 09:13:12.583802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f46bb79aa8a'
down_revision: Union[str, None] = '396b0f3249f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('rag_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'rag_content')
    # ### end Alembic commands ###
