"""add published_at

Revision ID: 4f65af5f2544
Revises: ac1c12af6d63
Create Date: 2026-04-19 19:39:09.049493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f65af5f2544'
down_revision: Union[str, None] = 'ac1c12af6d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'published_at')
    # ### end Alembic commands ###
